export enum CardTypes {
  DEBIT_SMART = 'debitSmart',
  DEBIT_TRAVEL = 'debitTravel',
  BILLABLE = 'billable',
  BILLABLE_PREMIUM = 'billablePremium',
}

export enum CardRequestTypes {
  DEBIT = 'Debit',
  CREDIT = 'Credit',
}

export enum GetCreditCardsInfoActions {
  GET_CREDIT_CARDS_INFO_REQUEST = 'GET_CREDIT_CARDS_INFO_REQUEST',
  GET_CREDIT_CARDS_INFO_SUCCESS = 'GET_CREDIT_CARDS_INFO_SUCCESS',
  GET_CREDIT_CARDS_INFO_ERROR = 'GET_CREDIT_CARDS_INFO_ERROR',
}

export enum GetDebitCardsInfoActions {
  GET_DEBIT_CARDS_INFO_REQUEST = 'GET_DEBIT_CARDS_INFO_REQUEST',
  GET_DEBIT_CARDS_INFO_SUCCESS = 'GET_DEBIT_CARDS_INFO_SUCCESS',
  GET_DEBIT_CARDS_INFO_ERROR = 'GET_DEBIT_CARDS_INFO_ERROR',
}

export enum OrderCreditPremium {
  ORDER_CREDIT_PREMIUM_REQUEST = 'ORDER_CREDIT_PREMIUM_REQUEST',
  ORDER_CREDIT_PREMIUM_SUCCESS = 'ORDER_CREDIT_PREMIUM_SUCCESS',
  ORDER_CREDIT_PREMIUM_ERROR = 'ORDER_CREDIT_PREMIUM_ERROR',
}

export enum OrderDebitCard {
  ORDER_DEBIT_CARD_REQUEST = 'ORDER_DEBIT_CARD_REQUEST',
  ORDER_DEBIT_CARD_SUCCESS = 'ORDER_DEBIT_CARD_SUCCESS',
  ORDER_DEBIT_CARD_ERROR = 'ORDER_DEBIT_CARD_ERROR',
}

export enum CardNames {
  DEBIT_SMART = 'Debit Smart card',
  DEBIT_TRAVEL = 'Debit Travel card',
  BILLABLE = 'Credit Card Billable',
  BILLABLE_PREMIUM = 'Credit Card Billable Premium',
}

export enum GetUserCardsActions {
  GET_USER_CARDS_REQUEST = 'GET_USER_CARDS_REQUEST',
  GET_USER_CARDS_SUCCESS = 'GET_USER_CARDS_SUCCESS',
  GET_USER_CARDS_ERROR = 'GET_USER_CARDS_ERROR',
}

export enum ChangeCardLimit {
  CHANGE_CARD_TRANSACTIONS_LIMIT_REQUEST = 'CHANGE_CARD_TRANSACTIONS_LIMIT_REQUEST',
  CHANGE_CARD_TRANSACTIONS_LIMIT_SUCCESS = 'CHANGE_CARD_TRANSACTIONS_LIMIT_SUCCESS',
  CHANGE_CARD_TRANSACTIONS_LIMIT_ERROR = 'CHANGE_CARD_TRANSACTIONS_LIMIT_ERROR',
}

export enum CardAmountFieldValidation {
  CARD_AMOUNT_FIELD_VALIDATION_REQUEST = 'CARD_AMOUNT_FIELD_VALIDATION_REQUEST',
  CARD_AMOUNT_FIELD_VALIDATION_SUCCESS = 'CARD_AMOUNT_FIELD_VALIDATION_SUCCESS',
  CARD_AMOUNT_FIELD_VALIDATION_ERROR = 'CARD_AMOUNT_FIELD_VALIDATION_ERROR',
}

export enum GetUserCardDetailsByIdActions {
  GET_USER_CARD_DETAILS_BY_ID_REQUEST = 'GET_USER_CARD_INFO_BY_ID_REQUEST',
  GET_USER_CARD_DETAILS_BY_ID_SUCCESS = 'GET_USER_CARD_INFO_BY_ID_SUCCESS',
  GET_USER_CARD_DETAILS_BY_ID_ERROR = 'GET_USER_CARD_INFO_BY_ID_ERROR',
  RESET_USER_CARD_DETAILS = 'RESET_USER_CARD_DETAILS',
}

export enum CardActivation {
  CARD_ACTIVATION_REQUEST = 'CARD_ACTIVATION_REQUEST',
  CARD_ACTIVATION_SUCCESS = 'CARD_ACTIVATION_SUCCESS',
  CARD_ACTIVATION_ERROR = 'CARD_ACTIVATION_ERROR',
}

export enum ChangeCardPinCode {
  CHANGE_CARD_PIN_CODE_REQUEST = 'CHANGE_CARD_PIN_CODE_REQUEST',
  CHANGE_CARD_PIN_CODE_SUCCESS = 'CHANGE_CARD_PIN_CODE_SUCCESS',
  CHANGE_CARD_PIN_CODE_ERROR = 'CHANGE_CARD_PIN_CODE_ERROR',
}
