export enum CardsHistory {
  CARD_HISTORY_REQUEST = 'CARD_HISTORY_REQUEST',
  CARD_HISTORY_SUCCESS = 'CARD_HISTORY_SUCCESS',
  CARD_HISTORY_ERROR = 'CARD_HISTORY_ERROR',
  CARD_FILTERED_DATA_REQUEST = 'CARD_FILTERED_DATA_REQUEST',
  CARD_FILTERED_DATA_SUCCESS = 'CARD_FILTERED_DATA_SUCCESS',
  CARD_FILTERED_DATA_ERROR = 'CARD_FILTERED_DATA_ERROR',
}
