export enum RoutingPaths {
  APPLY_LOAN = 'apply-loan',
  CARDS = 'cards',
  CARD_PRODUCTS = 'card-products',
  CARDS_APPLICATIONS = 'card-applications',
  CREDIT_CARDS = 'credit-cards',
  CREDIT_CARD_BILLABLE = 'billable',
  CREDIT_CARD_BILLABLE_PREMIUM = 'billable-premium',
  DEALS_OFFERS = 'deals-offers',
  DEBIT_CARDS = 'debit-cards',
  DEBIT_SMART_CARD = 'debit-smart-card',
  DEBIT_TRAVEL_CARD = 'debit-travel-card',
  DEPOSITS = 'deposits',
  INVESTING = 'investing',
  INSURANCE = 'insurance',
  MAIN_PAGE_URL = 'main-page',
  MY_CARDS = 'my-cards',
  MY_LOANS = 'my-loans',
  LOAN_PRODUCTS = 'loan-products',
  LOANS = 'loans',
  TRANSFERS = 'transfers',
  USER_ACCOUNT = 'user-account',
  CARD_DETAILS = 'card-details',
  PAGE_NOT_FOUND = 'page-not-found',
  CONTACTS = 'contacts',
}
