export enum TransactionsActions {
  GET_TRANSACTIONS_INFO_SUCCESS = 'GET_TRANSACTIONS_INFO_SUCCESS',
  GET_TRANSACTIONS_INFO_ERROR = 'GET_TRANSACTIONS_INFO_ERROR',
  GET_MAX_AMOUNT_VALUE_SUCCESS = 'GET_MAX_AMOUNT_VALUE_SUCCESS',
  GET_MAX_AMOUNT_VALUE_ERROR = 'GET_MAX_AMOUNT_VALUE_ERROR',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
}
