version: '3'

services:
  front:
    container_name: $PROJECT-$APP-$CI_COMMIT_BRANCH
    image: $AND_DOCKER_REGISTRY_NAME/$PROJECT-$APP:$CI_COMMIT_BRANCH
    env_file: $AND_ENV
    ports:
      - $PORT:$PORT
    restart: always
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        max-size: 300m
    networks:
      - amusic-2-new-net

networks:
  amusic-2-new-net:
    driver: bridge
